In [1]:
import os
import glob
import pandas as pd
import re

main_directory = os.path.normpath(os.getcwd() + os.sep + os.pardir)
data_directory = os.path.join(main_directory, 'TeamStats')
file_names = [f for f in os.listdir(data_directory) if os.path.isfile(os.path.join(data_directory, f))]
file_names

['2001Playoffs.csv',
 '2000Def.csv',
 '2012Def.csv',
 '2020Off.csv',
 '2020Adv.csv',
 '2014Playoffs.csv',
 '2008Playoffs.csv',
 '2004Off.csv',
 '2004Adv.csv',
 '2008Off.csv',
 '2008Adv.csv',
 '2016Off.csv',
 '2016Adv.csv',
 '2011Playoffs.csv',
 '2022Off.csv',
 '2022Adv.csv',
 '.DS_Store',
 '2014Off.csv',
 '2014Adv.csv',
 '2023Playoffs.csv',
 '2006Off.csv',
 '2006Adv.csv',
 '2018Off.csv',
 '2018Adv.csv',
 '2018Playoffs.csv',
 '2010Def.csv',
 '2004Playoffs.csv',
 '2002Def.csv',
 '2002Adv.csv',
 '2002Off.csv',
 '2007Playoffs.csv',
 '2010Adv.csv',
 '2010Off.csv',
 '2006Def.csv',
 '2018Def.csv',
 '2014Def.csv',
 '2020Playoffs.csv',
 '2022Def.csv',
 '2012Playoffs.csv',
 '2008Def.csv',
 '2016Def.csv',
 '2004Def.csv',
 '2017Playoffs.csv',
 '2020Def.csv',
 '2012Adv.csv',
 '2012Off.csv',
 '2002Playoffs.csv',
 '2000Adv.csv',
 '2000Off.csv',
 '2005Adv.csv',
 '2005Off.csv',
 '2017Adv.csv',
 '2017Off.csv',
 '2009Adv.csv',
 '2009Off.csv',
 '2005Playoffs.csv',
 '2021Adv.csv',
 '2019Playoffs.csv',
 '2021Off.csv',
 '2001Def.csv',
 '2022Playoffs.csv',
 '2013Def.csv',
 '2010Playoffs.csv',
 '2011Def.csv',
 '2009Playoffs.csv',
 '2003Def.csv',
 '2015Playoffs.csv',
 '2000Playoffs.csv',
 '2015Adv.csv',
 '2015Off.csv',
 'ChampionPrediction.ipynb',
 '2019Adv.csv',
 '2019Off.csv',
 '2007Adv.csv',
 '2007Off.csv',
 '2023Adv.csv',
 '2023Off.csv',
 '2023Def.csv',
 '2019Def.csv',
 '2007Def.csv',
 '2003Playoffs.csv',
 '2015Def.csv',
 '2016Playoffs.csv',
 '2003Off.csv',
 '2003Adv.csv',
 '2011Off.csv',
 '2011Adv.csv',
 '2013Playoffs.csv',
 '2013Off.csv',
 '2013Adv.csv',
 '2021Playoffs.csv',
 '2001Off.csv',
 '2001Adv.csv',
 '2021Def.csv',
 '2017Def.csv',
 '2006Playoffs.csv',
 '2009Def.csv',
 '2005Def.csv']

In [2]:
#lets read in 2000 def, adv,off, and playoffs


df_df = pd.read_csv(os.path.join(data_directory, '2000Def.csv'))
df_adv = pd.read_csv(os.path.join(data_directory, '2000Adv.csv'),header=1)
df_off = pd.read_csv(os.path.join(data_directory, '2000Off.csv'))
df_play = pd.read_csv(os.path.join(data_directory, '2000Playoffs.csv'),header=1)

In [3]:
df_df.head(10)

,Rk,Teamâ–²,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1.0,Atlanta Hawks,82,241.8,39.2,86.1,0.455,4.5,12.4,0.367,...,0.769,12.8,30.2,43.0,23.0,8.0,4.9,12.2,22.3,99.7
1,2.0,Boston Celtics,82,240.6,36.1,76.9,0.470,4.4,12.1,0.361,...,0.753,10.5,30.9,41.4,21.9,7.8,5.8,17.0,23.5,100.1
2,3.0,Charlotte Hornets*,82,241.2,37.2,83.1,0.448,5.0,13.2,0.378,...,0.745,11.8,31.1,42.9,23.2,7.4,5.1,15.8,25.3,95.8
3,4.0,Chicago Bulls,82,241.5,35.6,78.0,0.456,4.4,12.8,0.341,...,0.741,12.2,29.5,41.7,23.2,10.4,5.6,15.2,24.0,94.2
4,5.0,Cleveland Cavaliers,82,242.1,36.4,82.1,0.443,5.1,15.0,0.342,...,0.776,12.4,31.5,43.9,23.7,8.0,6.1,16.9,25.1,100.5
5,6.0,Dallas Mavericks,82,240.6,39.3,86.0,0.457,5.2,15.2,0.345,...,0.740,15.3,33.2,48.4,23.2,7.4,5.1,16.1,22.1,102.0
6,7.0,Denver Nuggets,82,242.1,38.2,84.8,0.450,4.9,13.7,0.354,...,0.751,12.5,31.8,44.3,24.4,7.5,5.6,14.4,23.6,101.1
7,8.0,Detroit Pistons*,82,241.8,38.0,81.8,0.465,5.6,15.0,0.371,...,0.746,11.9,30.5,42.4,23.1,8.0,4.8,17.1,27.1,102.0
8,9.0,Golden State Warriors,82,240.9,38.6,82.6,0.467,5.2,14.2,0.367,...,0.754,13.3,32.8,46.1,24.8,8.4,6.0,16.3,23.0,103.8
9,10.0,Houston Rockets,82,241.8,39.3,86.3,0.456,4.3,12.1,0.354,...,0.779,12.5,29.9,42.4,22.7,9.0,5.3,13.7,22.4,100.3

In [4]:
df_adv.head(10)

,Rk,Teamâ–²,Age,W,L,PW,PL,MOV,SOS,SRS,...,FT/FGA,Unnamed: 22,eFG%.1,TOV%.1,DRB%,FT/FGA.1,Unnamed: 27,Arena,Attend.,Attend./G
0,1.0,Atlanta Hawks,27.6,28.0,54.0,26,56,-5.38,-0.04,-5.41,...,0.217,NaN,0.481,11.3,71.0,0.196,NaN,Philips Arena,600954,14657
1,2.0,Boston Celtics,25.4,35.0,47.0,39,43,-0.76,-0.24,-1.00,...,0.236,NaN,0.498,15.8,73.8,0.306,NaN,FleetCenter,683608,16673
2,3.0,Charlotte Hornets*,28.7,49.0,33.0,49,33,2.67,-0.34,2.33,...,0.285,NaN,0.478,14.6,73.2,0.198,NaN,Charlotte Coliseum,732827,17874
3,4.0,Chicago Bulls,26.0,17.0,65.0,15,67,-9.40,0.17,-9.23,...,0.240,NaN,0.484,14.5,69.9,0.240,NaN,United Center,907064,22124
4,5.0,Cleveland Cavaliers,27.2,32.0,50.0,31,51,-3.50,-0.14,-3.64,...,0.245,NaN,0.474,15.1,71.2,0.275,NaN,Gund Arena,603702,14724
5,6.0,Dallas Mavericks,26.3,40.0,42.0,39,43,-0.57,0.29,-0.29,...,0.200,NaN,0.488,14.2,66.1,0.210,NaN,Reunion Arena,606177,14785
6,7.0,Denver Nuggets,25.9,35.0,47.0,35,47,-2.12,0.36,-1.76,...,0.222,NaN,0.479,13.0,71.6,0.235,NaN,Pepsi Center,637698,15554
7,8.0,Detroit Pistons*,28.3,42.0,40.0,45,37,1.44,-0.31,1.13,...,0.295,NaN,0.499,15.4,71.6,0.249,NaN,The Palace of Auburn Hills,678470,16548
8,9.0,Golden State Warriors,26.9,19.0,63.0,20,62,-8.27,0.64,-7.63,...,0.210,NaN,0.499,14.6,69.1,0.259,NaN,The Arena in Oakland,509171,12419
9,10.0,Houston Rockets,26.3,34.0,48.0,39,43,-0.87,0.30,-0.57,...,0.236,NaN,0.481,12.5,71.6,0.201,NaN,Compaq Center,624594,15234

In [5]:
df_off.head(10)

,Rk,Teamâ–²,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1.0,Atlanta Hawks,82,241.8,36.6,83.0,0.441,3.1,9.9,0.317,...,0.743,14.0,31.3,45.3,18.9,6.1,5.6,15.4,21.0,94.3
1,2.0,Boston Celtics,82,240.6,37.2,83.9,0.444,5.1,15.4,0.331,...,0.745,13.5,29.5,43.0,21.2,9.7,3.5,15.4,27.1,99.3
2,3.0,Charlotte Hornets*,82,241.2,35.8,79.7,0.449,4.1,12.2,0.339,...,0.758,10.8,32.1,42.9,24.7,8.9,5.9,14.7,20.4,98.4
3,4.0,Chicago Bulls,82,241.5,31.3,75.4,0.415,4.1,12.6,0.329,...,0.709,12.6,28.3,40.9,20.1,7.9,4.7,19.0,23.3,84.8
4,5.0,Cleveland Cavaliers,82,242.1,36.3,82.1,0.442,4.2,11.2,0.373,...,0.750,12.3,30.5,42.8,23.7,8.7,4.4,17.4,27.1,97.0
5,6.0,Dallas Mavericks,82,240.6,39.0,85.9,0.453,6.3,16.2,0.391,...,0.804,11.4,29.8,41.2,22.1,7.2,5.1,13.7,21.6,101.4
6,7.0,Denver Nuggets,82,242.1,37.3,84.3,0.442,5.7,17.0,0.336,...,0.724,13.1,31.6,44.7,23.3,6.8,7.5,15.6,23.9,99.0
7,8.0,Detroit Pistons*,82,241.8,37.1,80.9,0.459,5.4,14.9,0.359,...,0.781,11.2,30.0,41.2,20.8,8.1,3.3,15.7,24.5,103.5
8,9.0,Golden State Warriors,82,240.9,36.5,87.1,0.420,4.2,13.0,0.323,...,0.697,15.9,29.7,45.6,22.6,8.9,4.3,15.9,24.9,95.5
9,10.0,Houston Rockets,82,241.8,36.6,81.3,0.450,7.1,19.8,0.358,...,0.733,12.3,31.5,43.8,21.6,7.5,5.3,17.4,20.3,99.5

In [6]:
df_play.head(10)

,Rk,Team,Age,W,L,W/L%,PW,PL,ORtg,DRtg,...,Unnamed: 15,eFG%,TOV%,ORB%,FT/FGA,Unnamed: 20,eFG%.1,TOV%.1,DRB%,FT/FGA.1
0,1.0,Portland Trail Blazers,30.0,10.0,6.0,0.625,11,5,107.7,102.2,...,NaN,0.481,12.9,25.9,0.303,NaN,0.478,13.4,75.0,0.248
1,2.0,Miami Heat,29.6,6.0,4.0,0.600,6,4,97.4,94.4,...,NaN,0.451,14.1,25.7,0.227,NaN,0.431,13.5,80.8,0.269
2,3.0,Indiana Pacers,30.9,13.0,10.0,0.565,14,9,109.7,106.8,...,NaN,0.488,11.4,25.1,0.267,NaN,0.481,11.2,73.0,0.220
3,4.0,Los Angeles Lakers,29.3,15.0,8.0,0.652,13,10,110.1,107.5,...,NaN,0.498,11.4,30.6,0.245,NaN,0.476,12.1,73.7,0.289
4,5.0,Milwaukee Bucks,27.6,2.0,3.0,0.400,3,2,107.5,105.5,...,NaN,0.479,11.3,28.5,0.203,NaN,0.446,11.0,70.4,0.262
5,6.0,New York Knicks,29.7,9.0,7.0,0.563,7,9,99.8,101.1,...,NaN,0.462,12.5,20.3,0.243,NaN,0.442,12.5,73.3,0.250
6,7.0,Seattle Supersonics,27.9,2.0,3.0,0.400,2,3,104.5,105.8,...,NaN,0.481,14.0,28.7,0.209,NaN,0.508,15.5,71.9,0.214
7,8.0,San Antonio Spurs,31.0,1.0,3.0,0.250,2,2,90.0,91.4,...,NaN,0.391,15.4,26.5,0.293,NaN,0.421,14.5,70.8,0.149
8,9.0,Philadelphia 76ers,27.6,5.0,5.0,0.500,5,5,106.5,108.0,...,NaN,0.452,12.0,31.2,0.274,NaN,0.490,13.1,72.4,0.256
9,10.0,Minnesota Timberwolves,26.6,1.0,3.0,0.250,2,2,103.4,105.8,...,NaN,0.467,12.2,27.9,0.180,NaN,0.476,13.5,73.9,0.265

In [7]:
df_play.shape

(17, 25)

In [8]:
#seperate file names
off_files = [file for file in file_names if 'Off.csv' in file]
def_files = [file for file in file_names if 'Def.csv' in file]
adv_files = [file for file in file_names if 'Adv.csv' in file]
playoff_files = [file for file in file_names if 'Playoffs.csv' in file]

off_files = sorted(off_files)
def_files = sorted(def_files)
adv_files = sorted(adv_files)
playoff_files = sorted(playoff_files)

#initalize column headers and check if all file format is the same
off_header = df_off.columns
def_header = df_df.columns
adv_header = df_adv.columns
play_header = df_play.columns
off_header

Index(['Rk', 'Teamâ–²', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P',
       '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [9]:
#initalize some dataframe
df_offensive = pd.DataFrame()
df_defensive = pd.DataFrame()
df_playoff = pd.DataFrame()
df_advance = pd.DataFrame()


for i in range(len(off_files)):
    df = pd.read_csv(os.path.join(data_directory, off_files[i]))
    if df.columns.equals(off_header):
        df_offensive = pd.concat([df_offensive,df])
    else:
        print('this file header didnt match: ',off_files[i])
    
    df = pd.read_csv(os.path.join(data_directory, def_files[i]))
    if df.columns.equals(def_header):
        df_defensive = pd.concat([df_defensive,df])
    else:
        print('this file header didnt match: ',def_files[i])
        
    df = pd.read_csv(os.path.join(data_directory, adv_files[i]),header=1)
    if df.columns.equals(adv_header):
        df_advance = pd.concat([df_advance,df])
    else:
        print('this file header didnt match: ',adv_files[i])
        
    df = pd.read_csv(os.path.join(data_directory, playoff_files[i]),header=1)
    if df.columns.equals(play_header):
        df_playoff = pd.concat([df_playoff,df])
    else:
        print('this file header didnt match: ',playoff_files[i])

In [10]:
df_advance.shape

(739, 31)

In [11]:
df_playoff.shape

(412, 25)

In [12]:
df_defensive.shape

(739, 25)

In [13]:
df_offensive.shape

(739, 25)

In [14]:
df_advance.to_csv('team_adv.csv',header=True,index=False)
df_playoff.to_csv('team_playoff.csv',header=True,index=False)
df_defensive.to_csv('team_defensive.csv',header=True,index=False)
df_offensive.to_csv('team_offensive.csv',header=True,index=False)